### ISSUE TITLE
зачем вам last, если в node у вас нет prev?

### ISSUE THREAD

**Issue by coursar** [jafarsirojov/queue#2]
https://github.com/jafarsirojov/queue/blob/663c152e02971655d09f269495efe9ebb0c0cbcd/main.go#L5

**Comment by jafarsirojov** [comment]
Я использую last *queueNode
 https://github.com/jafarsirojov/queue/blob/663c152e02971655d09f269495efe9ebb0c0cbcd/main.go#L5
в двух функции(методов)
https://github.com/jafarsirojov/queue/blob/663c152e02971655d09f269495efe9ebb0c0cbcd/main.go#L69
https://github.com/jafarsirojov/queue/blob/663c152e02971655d09f269495efe9ebb0c0cbcd/main.go#L70
https://github.com/jafarsirojov/queue/blob/663c152e02971655d09f269495efe9ebb0c0cbcd/main.go#L73
https://github.com/jafarsirojov/queue/blob/663c152e02971655d09f269495efe9ebb0c0cbcd/main.go#L74

Если убрать last *queueNode тогда я не узнаю кто последний

**Comment by coursar** [comment]
ок, на лекции подойдите - объясню
